module.exports.list = [
  {
    name: 'Vanessa',
    country: 'Germany',
    role: 'Software Engineer',
    tech_stack: ['Python', 'Javascript', 'C++'],
    github_username: 'vaschindler',
    twitter_username: '#',
  },
  {
    name: 'Matheus Del Claro',
    country: 'Brazil',
    role: 'C.S. Graduated, Full-Stack developer',
    tech_stack: ['Node.js', 'React', 'React Native'],
    github_username: 'mdelclaro',
    twitter_username: 'mdelclaro',
  },
  {
    name: 'Yogesh Gupta',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['C++', 'Java'],
    github_username: 'Yg12061998',
    twitter_username: 'Yogi1206',
  },
  {
    name: 'Shubham',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['Node', 'JavaScript', 'Express'],
    github_username: 'shubham9019',
    twitter_username: '#',
  },
  {
    name: 'Jagreet',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['C++', 'Java', 'Android'],
    github_username: 'jagreetdg',
    twitter_username: '#',
  },
  {
    name: 'Urmilla',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: [
      'rently the file structure would look like this.Flutter',
      'JavaScript',
      'Express',
    ],
    github_username: 'urmilla20',
    twitter_username: '#',
  },
  {
    name: 'Mayank',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['Android', 'Java', 'Javascript'],
    github_username: 'mayankkhattar007',
    twitter_username: '#',
  },
  {
    name: 'Divanshi',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['Node', 'JavaScript', 'Express'],
    github_username: 'divanshi15',
    twitter_username: '#',
  },
  {
    name: 'Naivedh',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['Python', 'JavaScript', 'Java'],
    github_username: 'Naivedh',
    twitter_username: '#',
  },
  {
    name: 'Edvin',
    country: 'Bosnia and Herzegovina',
    role: 'Undergraduate',
    tech_stack: ['React', 'Node', 'Express'],
    github_username: 'PortaX',
    twitter_username: '# ',
  },
  {
    name: 'Mayank Kumar',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['JavaScript', 'Express'],
    github_username: 'mayank518',
    twitter_username: '#',
  },
  {
    name: 'Jitesh',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['Node', 'JavaScript', 'Express'],
    github_username: 'jiteshkumarr',
    twitter_username: '#',
  },
  {
    name: 'Desire',
    country: 'Zambia',
    role: 'Undergraduate',
    tech_stack: ['React', 'Python', 'C#'],
    github_username: 'Desire01',
    twitter_username: 'Chiefov1',
  },

  {
    name: 'Supun',
    country: 'Sri Lanka',
    role: 'Undergraduate',
    tech_stack: ['React', 'Node', 'Express'],
    github_username: 'chathuranga0307',
    twitter_username: '#',
  },
  {
    name: 'Alejandro García',
    country: 'España',
    role: 'To be filled',
    tech_stack: ['Swift', 'Laravel', 'JavaScript'],
    github_username: 'OwboxAl3x',
    twitter_username: '#',
  },
  {
    name: 'Wisnu Febriadi',
    country: 'Indonesia',
    role: 'To be filled',
    tech_stack: ['Flutter', 'Kotlin', 'Swift'],
    github_username: 'wfebriad',
    twitter_username: '#',
  },
  {
    name: 'Danielle Lyons',
    country: 'US',
    role: 'To be filled',
    tech_stack: ['JavaScript', 'Node', 'Express'],
    github_username: 'drding00',
    twitter_username: 'danachew',
  },
  {
    name: 'Arty',
    country: 'UK',
    role: 'To be filled',
    tech_stack: ['React', 'Redux', 'Sequelize ORM'],
    github_username: 'artysidorenko',
    twitter_username: 'PJSmooth3',
  },
  {
    name: 'Ankur Kalambe',
    country: 'United Kingdom',
    role: 'To be filled',
    tech_stack: ['Github', 'Robotics', 'Matlab'],
    github_username: 'ankurkalambe',
    twitter_username: 'ankur_kalambe',
  },
  {
    name: 'Ly Chunvira',
    country: 'Cambodia',
    role: 'To be filled',
    tech_stack: ['Python', 'Vue', 'React'],
    github_username: '#',
    twitter_username: '#',
  },
  {
    name: 'UMUT EKERDIKER',
    country: 'UNITED KINGDOM',
    role: 'To be filled',
    tech_stack: [
      'JavaScript',
      'MATLAB Deep learning',
      'Artificial Intelligence',
    ],
    github_username: 'RealBigpunch',
    twitter_username: 'MeisterShill',
  },
  {
    name: 'Silver',
    country: 'Earth',
    role: 'To be filled',
    tech_stack: ['React', 'Javascript', 'Css'],
    github_username: 'smarter23',
    twitter_username: '#',
  },
  {
    name: 'Anthony Kusuma',
    country: 'Indonesia',
    role: 'To be filled',
    tech_stack: ['ReactJS', 'Kotlin', 'Laravel'],
    github_username: 'anthonykusuma',
    twitter_username: 'actuallyaka',
  },
  {
    name: 'Shriyansh Jain',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['ReactJS', 'Machine Learning', 'Competitive Coding'],
    github_username: 'Shriyansh-J',
    twitter_username: '#',
  },
  {
    name: 'Nikhil Vaidyar',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['ReactJS', 'Golang', 'Graphql'],
    github_username: 'nikzayn',
    twitter_username: 'NikhilVaidyar',
  },
  {
    name: 'Kee Magbanua',
    country: 'Philippines',
    role: 'To be filled',
    tech_stack: ['JavaScript', 'React', 'Sass'],
    github_username: 'samcode23',
    twitter_username: 'zxcmoisturizer',
  },
  {
    name: 'Nikhil Gautam',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['ReactJS', 'Machine Learning', 'Qt'],
    github_username: 'nik-gautam',
    twitter_username: 'NikhilG30907544',
  },
  {
    name: 'Shynd',
    country: 'Norway',
    role: 'To be filled',
    tech_stack: ['C#', 'WPF', 'WCF'],
    github_username: 'Shynd',
    twitter_username: '#',
  },
  {
    name: 'Matteo F',
    country: 'Italy',
    role: 'To be filled',
    tech_stack: ['Laravel', 'Java', 'Python'],
    github_username: 'matteoformenti',
    twitter_username: '#',
  },
  {
    name: 'Aman Agarwal',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['Competitive Programming', 'React.Js', 'MongoDB'],
    github_username: 'BeastMaster07',
    twitter_username: 'amanag_007',
  },
  {
    name: 'Thanate',
    country: 'Thailand',
    tech_stack: ['JS', 'Vue', 'Ruby'],
    github_username: 'mugenboat',
    twitter_username: '#',
  },
  {
    name: 'Jay Parmani',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['NodeJS', 'React Native', 'Blockchain'],
    github_username: 'jsparmani',
    twitter_username: 'jsparmani',
  },
  {
    name: 'Pranshu Kharkwal',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['NodeJS', 'React Native', 'Blockchain'],
    github_username: 'pranshukharkwal',
    twitter_username: 'hellopranshu',
  },
  {
    name: 'Aditya Kumar Singh',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['Django', 'Arduino', 'Angular.js'],
    github_username: 'adityakumar2809',
    twitter_username: 'adityakumar2809',
  },
  {
    name: 'Sibin',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['Android', 'Java', 'Javascript', 'NodeJs'],
    github_username: 'sibinjoseph111',
    twitter_username: 'sibin__',
  },
  {
    name: 'Mikalai Sokarau',
    country: 'Belarus',
    role: 'To be filled',
    tech_stack: ['JS', 'HTML', 'CSS'],
    github_username: 'mikalai-sokarau',
    twitter_username: 'nope',
  },
  {
    name: 'Luis Takahashi',
    country: 'Brazil',
    role: 'To be filled',
    tech_stack: ['Js', 'React', 'Typescript'],
    github_username: 'luistak',
    twitter_username: '_luistak',
  },
  {
    name: 'Akash Kumar',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['Python', 'C++', 'Machine Learning'],
    github_username: 'aaakashkumar',
    twitter_username: 'piratedvirus09',
  },
  {
    name: 'Gaurav',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['Angular', 'Node', 'Express'],
    github_username: 'grvv',
    twitter_username: '#',
  },
  {
    name: 'Yatharth',
    country: 'India',
    role: 'To be Filled',
    tech_stack: ['ReactJS', 'Node', 'Express'],
    github_username: 'yatharth17',
    twitter_username: '#',
  },
  {
    name: 'Michael',
    country: 'United States of America',
    role: 'To be filled',
    tech_stack: ['HTML5', 'CSS3', 'JavaScript (ES6)'],
    github_username: '9112Michael',
    twitter_username: '#',
  },
  {
    name: 'Rajprakash',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['ReactJS', 'Competitive Programming', 'BurpSuite'],
    github_username: 'rajprakash00',
    twitter_username: 'RajprakashSahoo',
  },
  {
    name: 'Kevin Nathaniel',
    country: 'Indonesia',
    role: 'To be filled',
    tech_stack: ['ReactJS', 'Java', 'PostgreSQL'],
    github_username: 'kevin2000141',
    twitter_username: '-',
  },
  {
    name: 'Saeed',
    country: 'Iran',
    role: 'Mobile Developer',
    tech_stack: ['Android', 'iOS', 'Node'],
    github_username: 'saeed-rz',
    twitter_username: '@SaeedRezaeii',
  },
  {
    name: 'Riya',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['MongoDB', 'Express', 'Node'],
    github_username: 'Icor101',
    twitter_username: '#',
  },
  {
    name: 'Shyam Unnikrishnan',
    country: 'India',
    role: 'Full Stack Developer',
    tech_stack: ['MongoDB', 'Express', 'Node', 'VueJS'],
    github_username: 'shyamunnikrishnan',
    twitter_username: 'shyam_uk',
  },
  {
    name: 'Lun Zhang',
    country: 'United States',
    role: 'Frontend Engineer',
    tech_stack: ['Javascript', 'Node', 'react'],
    github_username: 'lunzhang',
    twitter_username: '#',
  },
  {
    name: 'Riya',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['MongoDB', 'Express', 'Node'],
    github_username: 'Icor101',
    twitter_username: '#',
  },
  {
    name: 'Samuel Owad',
    country: 'Nigeria',
    tech_stack: ['Js', 'React', 'Node'],
    github_username: 'samuelowad',
    twitter_username: '',
  },
  {
    name: 'Vishal',
    country: 'India',
    role: 'To be filled',
    tech_stack: ['Machine learning', 'Python', 'Java'],
    github_username: 'Vishalyadav0804',
    twitter_username: '#',
  },
  {
    name: 'M. Oliveira',
    country: 'Portugal',
    role: 'full stack software dev',
    tech_stack: ['java', 'javascript', 'python', 'react'],
    github_username: 'm-oliv',
    twitter_username: '#',
  },
  {
    name: 'Abhay',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['C++', 'JavaScript', 'HTML', 'CSS'],
    github_username: 'abhay27chauhan',
    twitter_username: '#',
  },
  {
    name: 'Upasana Deka',
    country: 'India',
    role: 'Undergrad Web Developer',
    tech_stack: ['C++', 'Python', 'JavaScript', 'React'],
    github_username: 'upasanadeka',
    twitter_username: 'upasana_deka',
  },
  {
    name: 'Siddhant',
    country: 'India',
    role: 'Full stack web developer',
    tech_stack: ['JavaScGauravript', 'MaterializeCSS', 'Node'],
    github_username: 'FuzzySid',
    twitter_username: '#',
  },
  {
    name: 'Ricardo Dantas',
    country: 'Brazil',
    role: 'Full stack web developer',
    tech_stack: ['Python', 'Django', 'JavaScript', 'MaterializeCSS', 'NodeJS'],
    github_username: 'licensed',
    twitter_username: 'licensed',
  },
  {
    name: 'Jugal',
    country: 'India',
    role: 'Full Stack Developer',
    tech_stack: ['Python', 'Django', 'Flask', 'C', 'C++', 'Node'],
    github_username: 'tmw9',
    twitter_username: 'tmw9',
  },
  {
    name: 'Tiho Banov',
    country: 'Bulgaria',
    role: 'Full stack web developer',
    tech_stack: ['PHP', 'JavaScript', 'NodeJS'],
    github_username: 'tbanov',
    twitter_username: '',
  },
  {
    name: 'LucasOe',
    country: 'Germany',
    role: 'Frontend Developer',
    tech_stack: ['Java', 'NodeJS', 'HTML'],
    github_username: 'LucasOe',
    twitter_username: '_LucasOe_',
  },
  {
    name: 'Camilo Caquimbo',
    country: 'Colombia',
    role: 'Full stack',
    tech_stack: ['PHP', 'JavaScript', 'Laravel'],
    github_username: 'camilocaquimbo',
    twitter_username: 'ccaquimbo',
  },
  {
    name: 'Phong Duong',
    country: 'Viet Nam',
    role: 'Fullstack Developer',
    tech_stack: ['NodeJS', 'VueJS', 'ReactJS', 'Firebase'],
    github_username: 'phongduong',
    twitter_username: 'phong_lh_duong',
  },
  {
    name: 'Balu M N',
    country: 'India',
    role: 'Python Developer',
    tech_stack: ['Django', 'Flask', 'ReactJS'],
    github_username: 'balumn',
    twitter_username: 'BaluMNandakumar',
  },
  {
    name: 'Kunal Katiyar',
    country: 'India',
    role: 'Python Developer',
    tech_stack: ['Django', 'Selenium', 'Scrapy'],
    github_username: 'kunalkatiyar',
    twitter_username: 'KunalKatiyar',
  },
  {
    name: 'gian hays',
    country: 'Indonesia',
    role: 'Fullstack Developer',
    tech_stack: ['Javascript', 'NodeJS', 'Python'],
    github_username: 'ardiraika',
    twitter_username: '',
  },
  {
    name: 'Vishakha Bansal',
    country: 'India',
    role: 'web developer',
    tech_stack: ['java', 'c++', 'html/css', 'opencv'],
    github_username: 'vbansal20',
    twitter_username: '#',
  },
  {
    name: 'Mayank',
    country: 'India',
    role: 'Android Developer',
    tech_stack: ['Python', 'Java'],
    github_username: 'mayank97',
    twitter_username: 'mayank_mk18',
  },
  {
    name: 'Lilian Ferreira',
    country: 'Spain',
    role: 'To be filled',
    tech_stack: ['Java', 'Javascript', 'Python'],
    github_username: 'lilianferreira',
    twitter_username: 'lilianferreira',
  },
  {
    name: 'Soumaya Ranjan',
    country: 'India',
    role: 'Full-Stack Developer',
    tech_stack: ['LAMP', 'iOS', 'ionic-cordova'],
    github_username: 'bojack-horseman',
    twitter_username: 'big_daddy2802',
  },
  {
    name: 'Patrick',
    country: 'USA',
    role: 'student',
    tech_stack: ['Java', 'Python'],
    github_username: 'cspatrick',
    twitter_username: '',
  },
  {
    name: 'Mudit Nagar',
    country: 'India',
    role: 'UI Developer',
    tech_stack: ['HTML', 'CSS', 'Javascript'],
    github_username: 'mdtngr',
    twitter_username: '_',
  },
  {
    name: 'Tedo Haris Chandra',
    country: 'Indonesia',
    role: 'Web Developer',
    tech_stack: ['HTML/CSS', 'Laravel', 'Javascript'],
    github_username: 'TedoHarisC',
    twitter_username: 'tedo_hc29',
  },
  {
    name: 'Sahil Manchanda',
    country: 'India',
    role: 'Android Developer',
    tech_stack: ['Firebase', 'java', 'c++'],
    github_username: 'sahilmanchanda1999',
    twitter_username: '#',
  },
  {
    name: 'Abhishek',
    country: 'India',
    role: 'Software/Firmware Engineer',
    tech_stack: ['C', 'Java', 'Python'],
    github_username: 'unkemptArc99',
    twitter_username: 'unkemptArc99',
  },
  {
    name: 'Mayank Mani',
    country: 'India',
    role: 'ML engineer',
    tech_stack: ['Python', 'Scikit', 'C++'],
    github_username: 'MayankMani00',
    twitter_username: '#',
  },
  {
    name: 'Avinish Kumar',
    country: 'India',
    role: 'Full Stack Developer',
    tech_stack: ['Node.js', 'C++', 'Pyhton'],
    github_username: 'avi-01',
    twitter_username: '#',
  },
  {
    name: 'Subham Agrawal',
    country: 'India',
    role: 'Software Engineer',
    tech_stack: ['Node.js', 'C++', 'C', 'Javascript'],
    github_username: 'subhamagrawal7',
    twitter_username: '#Subham_Agrawal4',
  },
  {
    name: 'Alfons Hwu',
    country: 'Taiwan',
    role: 'Student',
    tech_stack: ['ShellScript', 'C/C++', 'Pyhton', 'PyTorch', 'Verilog'],
    github_username: 'Alfons0329',
    twitter_username: '#',
  },
  {
    name: 'Prakhar Sapre',
    country: 'USA',
    role: 'Professional',
    tech_stack: ['Java'],
    github_username: 'prakhar10',
    twitter_username: '#',
  },
  {
    name: 'Ahmed',
    country: 'Egypt',
    role: 'Undergraduate',
    tech_stack: ['C++', 'Python'],
    github_username: 'ahmibr',
    twitter_username: '#',
  },
  {
    name: 'Shoba',
    country: 'India',
    role: 'UI Engineer',
    tech_stack: ['HTML', 'Javascript', 'React'],
    github_username: 'ShobaS',
    twitter_username: '#',
  },
  {
    name: 'Jui',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['C++', 'Python'],
    github_username: 'shahjui2000',
    twitter_username: '#',
  },
  {
    name: 'Tikam Singh Alma',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['C++', 'Python', 'Go'],
    github_username: 'Tikam02',
    twitter_username: 'n3ur0mancer',
  },
  {
    name: 'Pankil Panchal',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['C++', 'Python', 'Nodejs', 'Expressjs', 'Reactjs'],
    github_username: 'pcube99',
    twitter_username: 'p_cube99',
  },
  {
    name: 'Rafael',
    country: 'Spain',
    role: 'Software',
    tech_stack: ['Java', 'Python', 'Perl', 'Data Science', 'MiPollaEnVinagre'],
    github_username: 'rafagarciac',
    twitter_username: '#',
  },
  {
    name: 'Anmol',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['C++', 'Flutter', 'RPA'],
    github_username: 'garganmol111',
    twitter_username: '#',
  },
  {
    name: 'Jeethendra',
    country: 'India',
    role: 'Sophomore/Android Developer',
    tech_stack: ['C++', 'Python', 'Angularjs', 'Java', 'HTML & CSS'],
    github_username: 'JeeBoomBoi',
    twitter_username: 'JeethendraB',
  },
  {
    name: 'Abhisht',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['C++', 'JAVA'],
    github_username: 'abhishtjoshi',
    twitter_username: '#',
  },
  {
    name: 'Paras',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['C++', 'C'],
    github_username: 'parasmannan',
    twitter_username: '#',
  },
  {
    name: 'Arun Kumar',
    country: 'India',
    role: 'Undergraduate',
    tech_stack: ['C++', 'Python', 'Javascript'],
    github_username: 'Arun179',
    twitter_username: '#',
  },
  {
    name: 'Edwin Harly',
    country: 'Indonesia',
    role: 'Full-Stack developer',
    tech_stack: ['Node.js', 'React', 'Vue', 'Mule ESB'],
    github_username: 'edwinharly',
    twitter_username: '#',
  },
  {
    name: 'Johanes Boas Badia',
    country: 'Indonesia',
    role: 'Undergraduate',
    tech_stack: ['Java', 'C++', 'Python'],
    github_username: 'boasmarbun',
    twitter_username: '#',
  },
  {
    name: 'Lenoir Christopher',
    country: 'France',
    role: 'Developer fullstack',
    tech_stack: ['Javascript', 'Php', 'C++', 'Python'],
    github_username: 'xLeDocteurx',
    twitter_username: '#',
  },
  {
    name: 'Derek',
    country: 'Malaysia',
    role: 'Student',
    tech_stack: ['C', 'C++', 'Java'],
    github_username: 'Quanta770',
    twitter_username: '#',
  },
  {
    name: 'Nori Khan',
    country: 'Canada',
    role: 'To be filled',
    tech_stack: ['Java', 'JavaScript', 'SQL'],
    github_username: 'naorinn',
    twitter_username: '#',
  },
  {
    name: 'dfarley1',
    country: 'USA',
    role: 'Software Developer',
    tech_stack: ['C', 'C++', 'Python'],
    github_username: 'dfarley1',
    twitter_username: '#',
  },
  {
    name: 'Pritesh Tripathi',
    country: 'India',
    role: 'Student',
    tech_stack: ['Node js', 'C++', 'Javascrip'],
    github_username: 'priteshtripathi7',
    twitter_username: '#',
  },
  {
    name: 'Nguyen',
    country: 'Vietnam',
    role: 'Software Developer',
    tech_stack: ['Javascript', 'Nodejs', 'React'],
    github_username: 'damdauvaotran',
    twitter_username: '#',
  },
  {
    name: 'Nicholas Huber',
    country: 'USA',
    role: 'Full-Stack developer',
    tech_stack: ['Node.js', 'React', 'React Native'],
    github_username: 'nicholashuber',
    twitter_username: 'imnickhuber',
  },
  {
    name: 'Chavez',
    country: 'Student',
    role: 'Student',
    tech_stack: ['Web Development', 'Java', 'JavaScript', 'PHP'],
    github_username: 'joschavz',
    twitter_username: '#',
  }
];
