export const contributors = [
  {
    name: "Sabahat iqbal",
    github_username: "SabahatPK",
    favorite_coding_stack: ["Javascript", "React", "Python"],
    about_me: "",
  },
  {
    name: "Sethu Narayan Senthil",
    github_username: "sethusenthil",
    favorite_coding_stack: ["NodeJs", "React", "Dart", "Swift"],
    about_me: "",
  },
  {
    name: "Samer",
    github_username: "S4M3R",
    favorite_coding_stack: ["NodeJs", "VB.NET", "Java", "Python"],
    about_me: "",
  },
  {
    name: "Ismailtlem",
    github_username: "Ismailtlem",
    favorite_coding_stack: ["NodeJs", "Javascript", "ReactJS", "Python"],
    about_me: "",
  },
  {
    name: "Fathurrahnan",
    github_username: "nersus15",
    favorite_coding_stack: ["NodeJs", "PHP", "Java", "ReactJs"],
    about_me: "",
  },
  {
    name: "deeprajpandey",
    github_username: "deeprajpandey",
    favorite_coding_stack: ["C", "C++", "python", "gem5"],
    about_me: "",
  },
  {
    name: "vijaygorfad",
    github_username: "gorfadvijay",
    favorite_coding_stack: ["C", "C++", "python", "Js"],
    about_me: "",
  },
  {
    name: "jrab66",
    github_username: "jrab66",
    favorite_coding_stack: ["python", "IAC", "terraform"],
    about_me: "",
  },
  {
    name: "HakaCode",
    github_username: "HakaCode",
    favorite_coding_stack: ["JS", "HTML", "CSS"],
    about_me: "",
  },
  {
    name: "maurizio",
    github_username: "ibbatta",
    favorite_coding_stack: ["AngularJs", "React", "Javascript", "Node"],
    about_me: "",
  },
  {
    name: "Henrique",
    github_username: "lhenrique42",
    favorite_coding_stack: ["Python", "Java", "C", "JavaScript"],
    about_me: "",
  },
  {
    name: "Sam",
    github_username: "samx81",
    favorite_coding_stack: ["Python"],
    about_me: "",
  },
  {
    name: "Rafael",
    github_username: "baronrafael",
    favorite_coding_stack: ["Angular", "NativeScript", "React Native"],
    about_me: "",
  },
  {
    name: "Matheus",
    github_username: "matheusafonsouza",
    favorite_coding_stack: ["C", "C++", "Python", "Java", "Ruby"],
    about_me: "",
  },
  {
    name: "Vanessa",
    github_username: "vaschindler",
    favorite_coding_stack: ["Python", "Javascript", "C++"],
    about_me: "",
  },
  {
    name: "Mateus Gomes do Nascimento",
    github_username: "matgomes21",
    favorite_coding_stack: ["C", "C++", "Java"],
    about_me: "",
  },
  {
    name: "Arend",
    github_username: "arendestes",
    favorite_coding_stack: ["Javascript"],
    about_me: "",
  },
  {
    name: "Matheus Del Claro",
    github_username: "mdelclaro",
    favorite_coding_stack: ["Node.js", "React", "React Native"],
    about_me: "",
  },
  {
    name: "Joe Ma. Aubrey A. Nequinto",
    github_username: "JoemaNequinto",
    favorite_coding_stack: ["Node.js", "React Native"],
    about_me: "",
  },
  {
    name: "Yogesh Gupta",
    github_username: "Yg12061998",
    favorite_coding_stack: ["C++", "Java"],
    about_me: "",
  },
  {
    name: "Shubham",
    github_username: "shubham9019",
    favorite_coding_stack: ["Node", "JavaScript", "Express"],
    about_me: "",
  },
  {
    name: "Jagreet",
    github_username: "jagreetdg",
    favorite_coding_stack: ["C++", "Java", "Android"],
    about_me: "",
  },
  {
    name: "Urmilla",
    github_username: "urmilla20",
    favorite_coding_stack: ["Flutter", "JavaScript", "Express"],
    about_me: "",
  },
  {
    name: "Mayank",
    github_username: "mayankkhattar007",
    favorite_coding_stack: ["Android", "Java", "Javascript"],
    about_me: "",
  },
  {
    name: "Divanshi",
    github_username: "divanshi15",
    favorite_coding_stack: ["Node", "JavaScript", "Express"],
    about_me: "",
  },
  {
    name: "Naivedh",
    github_username: "Naivedh",
    favorite_coding_stack: ["Python", "JavaScript", "Java"],
    about_me: "",
  },
  {
    name: "Edvin",
    github_username: "PortaX",
    favorite_coding_stack: ["React", "Node", "Express"],
    about_me: "",
  },
  {
    name: "Mayank Kumar",
    github_username: "mayank518",
    favorite_coding_stack: ["JavaScript", "Express"],
    about_me: "",
  },
  {
    name: "Jitesh",
    github_username: "jiteshkumarr",
    favorite_coding_stack: ["Node", "JavaScript", "Express"],
    about_me: "",
  },
  {
    name: "Desire",
    github_username: "Desire01",
    favorite_coding_stack: ["React", "Python", "C#"],
    about_me: "",
  },
  {
    name: "Jamille Bittencourt",
    github_username: "millbittencourt",
    favorite_coding_stack: ["C#", "Java"],
    about_me: "",
  },
  {
    name: "Supun",
    github_username: "chathuranga0307",
    favorite_coding_stack: ["React", "Node", "Express"],
    about_me: "",
  },
  {
    name: "Alejandro García",
    github_username: "OwboxAl3x",
    favorite_coding_stack: ["Swift", "Laravel", "JavaScript"],
    about_me: "",
  },
  {
    name: "Wisnu Febriadi",
    github_username: "wfebriad",
    favorite_coding_stack: ["Flutter", "Kotlin", "Swift"],
    about_me: "",
  },
  {
    name: "Danielle Lyons",
    github_username: "drding00",
    favorite_coding_stack: ["JavaScript", "Node", "Express"],
    about_me: "",
  },
  {
    name: "Arty",
    github_username: "artysidorenko",
    favorite_coding_stack: ["React", "Redux", "Sequelize ORM"],
    about_me: "",
  },
  {
    name: "Ankur Kalambe",
    github_username: "ankurkalambe",
    favorite_coding_stack: ["Github", "Robotics", "Matlab"],
    about_me: "",
  },
  {
    name: "Ly Chunvira",
    github_username: "#",
    favorite_coding_stack: ["Python", "Vue", "React"],
    about_me: "",
  },
  {
    name: "UMUT EKERDIKER",
    github_username: "RealBigpunch",
    favorite_coding_stack: [
      "JavaScript",
      "MATLAB Deep learning",
      "Artificial Intelligence",
    ],
    about_me: "",
  },
  {
    name: "Silver",
    github_username: "smarter23",
    favorite_coding_stack: ["React", "Javascript", "Css"],
    about_me: "",
  },
  {
    name: "Anthony Kusuma",
    github_username: "anthonykusuma",
    favorite_coding_stack: ["ReactJS", "Kotlin", "Laravel"],
    about_me: "",
  },
  {
    name: "Shriyansh Jain",
    github_username: "Shriyansh-J",
    favorite_coding_stack: ["ReactJS", "Machine Learning", "Competitive Coding"],
    about_me: "",
  },
  {
    name: "Nikhil Vaidyar",
    github_username: "nikzayn",
    favorite_coding_stack: ["ReactJS", "Golang", "Graphql"],
    about_me: "",
  },
  {
    name: "Kee Magbanua",
    github_username: "samcode23",
    favorite_coding_stack: ["JavaScript", "React", "Sass"],
    about_me: "",
  },
  {
    name: "Nikhil Gautam",
    github_username: "nik-gautam",
    favorite_coding_stack: ["ReactJS", "Machine Learning", "Qt"],
    about_me: "",
  },
  {
    name: "Shynd",
    github_username: "Shynd",
    favorite_coding_stack: ["C#", "WPF", "WCF"],
    about_me: "",
  },
  {
    name: "Matteo F",
    github_username: "matteoformenti",
    favorite_coding_stack: ["Laravel", "Java", "Python"],
    about_me: "",
  },
  {
    name: "Aman Agarwal",
    github_username: "BeastMaster07",
    favorite_coding_stack: ["Competitive Programming", "React.Js", "MongoDB"],
    about_me: "",
  },
  {
    name: "Ashwin P",
    github_username: "ashwin74",
    favorite_coding_stack: ["JavaScript", "C", "ReactJS"],
    about_me: "",
  },
  {
    name: "Thanate",
    github_username: "mugenboat",
    favorite_coding_stack: ["JS", "Vue", "Ruby"],
    about_me: "",
  },
  {
    name: "Jay Parmani",
    github_username: "jsparmani",
    favorite_coding_stack: ["NodeJS", "React Native", "Blockchain"],
    about_me: "",
  },
  {
    name: "Pranshu Kharkwal",
    github_username: "pranshukharkwal",
    favorite_coding_stack: ["NodeJS", "React Native", "Blockchain"],
    about_me: "",
  },
  {
    name: "Aditya Kumar Singh",
    github_username: "adityakumar2809",
    favorite_coding_stack: ["Django", "Arduino", "Angular.js"],
    about_me: "",
  },
  {
    name: "Sibin",
    github_username: "sibinjoseph111",
    favorite_coding_stack: ["Android", "Java", "Javascript", "NodeJs"],
    about_me: "",
  },
  {
    name: "Mikalai Sokarau",
    github_username: "mikalai-sokarau",
    favorite_coding_stack: ["JS", "HTML", "CSS"],
    about_me: "",
  },
  {
    name: "Luis Takahashi",
    github_username: "luistak",
    favorite_coding_stack: ["Js", "React", "Typescript"],
    about_me: "",
  },
  {
    name: "Akash Kumar",
    github_username: "aaakashkumar",
    favorite_coding_stack: ["Python", "C++", "Machine Learning"],
    about_me: "",
  },
  {
    name: "Gaurav",
    github_username: "grvv",
    favorite_coding_stack: ["Angular", "Node", "Express"],
    about_me: "",
  },
  {
    name: "Yatharth",
    github_username: "yatharth17",
    favorite_coding_stack: ["ReactJS", "Node", "Express"],
    about_me: "",
  },
  {
    name: "Michael",
    github_username: "9112Michael",
    favorite_coding_stack: ["HTML5", "CSS3", "JavaScript (ES6)"],
    about_me: "",
  },
  {
    name: "Rajprakash",
    github_username: "rajprakash00",
    favorite_coding_stack: ["ReactJS", "Competitive Programming", "BurpSuite"],
    about_me: "",
  },
  {
    name: "Kevin Nathaniel",
    github_username: "kevin2000141",
    favorite_coding_stack: ["ReactJS", "Java", "PostgreSQL"],
    about_me: "",
  },
  {
    name: "Saeed",
    github_username: "saeed-rz",
    favorite_coding_stack: ["Android", "iOS", "Node"],
    about_me: "",
  },
  {
    name: "Riya",
    github_username: "Icor101",
    favorite_coding_stack: ["MongoDB", "Express", "Node"],
    about_me: "",
  },
  {
    name: "Pedro Veríssimo",
    github_username: "pbv2",
    favorite_coding_stack: ["HTML5, CSS3, JavaScript ", "C++/C#", "Python <3"],
    about_me: "",
  },
  {
    name: "Shyam Unnikrishnan",
    github_username: "shyamunnikrishnan",
    favorite_coding_stack: ["MongoDB", "Express", "Node", "VueJS"],
    about_me: "",
  },
  {
    name: "Lun Zhang",
    github_username: "lunzhang",
    favorite_coding_stack: ["Javascript", "Node", "react"],
    about_me: "",
  },
  {
    name: "Riya",
    github_username: "Icor101",
    favorite_coding_stack: ["MongoDB", "Express", "Node"],
    about_me: "",
  },
  {
    name: "Samuel Owad",
    github_username: "samuelowad",
    favorite_coding_stack: ["Js", "React", "Node"],
    about_me: "",
  },
  {
    name: "Vishal",
    github_username: "Vishalyadav0804",
    favorite_coding_stack: ["Machine learning", "Python", "Java"],
    about_me: "",
  },
  {
    name: "M. Oliveira",
    github_username: "m-oliv",
    favorite_coding_stack: ["java", "javascript", "python", "react"],
    about_me: "",
  },
  {
    name: "Abhay",
    github_username: "abhay27chauhan",
    favorite_coding_stack: ["C++", "JavaScript", "HTML", "CSS"],
    about_me: "",
  },
  {
    name: "Upasana Deka",
    github_username: "upasanadeka",
    favorite_coding_stack: ["C++", "Python", "JavaScript", "React"],
    about_me: "",
  },
  {
    name: "Siddhant",
    github_username: "FuzzySid",
    favorite_coding_stack: ["JavaScGauravript", "MaterializeCSS", "Node"],
    about_me: "",
  },
  {
    name: "Ricardo Dantas",
    github_username: "licensed",
    favorite_coding_stack: ["Python", "Django", "JavaScript", "MaterializeCSS", "NodeJS"],
    about_me: "",
  },
  {
    name: "Jugal",
    github_username: "tmw9",
    favorite_coding_stack: ["Python", "Django", "Flask", "C", "C++", "Node"],
    about_me: "",
  },
  {
    name: "Tiho Banov",
    github_username: "tbanov",
    favorite_coding_stack: ["PHP", "JavaScript", "NodeJS"],
    about_me: "",
  },
  {
    name: "Bjarkt",
    github_username: "bjarkt",
    favorite_coding_stack: ["Java", "JavaScript", "HTML/CSS", "NodeJS", "PHP", "SQL"],
    about_me: "",
  },
  {
    name: "LucasOe",
    github_username: "LucasOe",
    favorite_coding_stack: ["Java", "NodeJS", "HTML"],
    about_me: "",
  },
  {
    name: "Camilo Caquimbo",
    github_username: "camilocaquimbo",
    favorite_coding_stack: ["PHP", "JavaScript", "Laravel"],
    about_me: "",
  },
  {
    name: "Phong Duong",
    github_username: "phongduong",
    favorite_coding_stack: ["NodeJS", "VueJS", "ReactJS", "Firebase"],
    about_me: "",
  },
  {
    name: "Balu M N",
    github_username: "balumn",
    favorite_coding_stack: ["Django", "Flask", "ReactJS"],
    about_me: "",
  },
  {
    name: "Kunal Katiyar",
    github_username: "kunalkatiyar",
    favorite_coding_stack: ["Django", "Selenium", "Scrapy"],
    about_me: "",
  },
  {
    name: "gian hays",
    github_username: "ardiraika",
    favorite_coding_stack: ["Javascript", "NodeJS", "Python"],
    about_me: "",
  },
  {
    name: "Vishakha Bansal",
    github_username: "vbansal20",
    favorite_coding_stack: ["java", "c++", "html/css", "opencv"],
    about_me: "",
  },
  {
    name: "Mayank",
    github_username: "mayank97",
    favorite_coding_stack: ["Python", "Java"],
    about_me: "",
  },
  {
    name: "Lilian Ferreira",
    github_username: "lilianferreira",
    favorite_coding_stack: ["Java", "Javascript", "Python"],
    about_me: "",
  },
  {
    name: "Soumaya Ranjan",
    github_username: "bojack-horseman",
    favorite_coding_stack: ["LAMP", "iOS", "ionic-cordova"],
    about_me: "",
  },
  {
    name: "Patrick",
    github_username: "cspatrick",
    favorite_coding_stack: ["Java", "Python"],
    about_me: "",
  },
  {
    name: "Mudit Nagar",
    github_username: "mdtngr",
    favorite_coding_stack: ["HTML", "CSS", "Javascript"],
    about_me: "",
  },
  {
    name: "Tedo Haris Chandra",
    github_username: "TedoHarisC",
    favorite_coding_stack: ["HTML/CSS", "Laravel", "Javascript"],
    about_me: "",
  },
  {
    name: "Sahil Manchanda",
    github_username: "sahilmanchanda1999",
    favorite_coding_stack: ["Firebase", "java", "c++"],
    about_me: "",
  },
  {
    name: "Abhishek",
    github_username: "unkemptArc99",
    favorite_coding_stack: ["C", "Java", "Python"],
    about_me: "",
  },
  {
    name: "Mayank Mani",
    github_username: "MayankMani00",
    favorite_coding_stack: ["Python", "Scikit", "C++"],
    about_me: "",
  },
  {
    name: "Avinish Kumar",
    github_username: "avi-01",
    favorite_coding_stack: ["Node.js", "C++", "Pyhton"],
    about_me: "",
  },
  {
    name: "Subham Agrawal",
    github_username: "subhamagrawal7",
    favorite_coding_stack: ["Node.js", "C++", "C", "Javascript"],
    about_me: "",
  },
  {
    name: "Alfons Hwu",
    github_username: "Alfons0329",
    favorite_coding_stack: ["ShellScript", "C/C++", "Pyhton", "PyTorch", "Verilog"],
    about_me: "",
  },
  {
    name: "Prakhar Sapre",
    github_username: "prakhar10",
    favorite_coding_stack: ["Java"],
    about_me: "",
  },
  {
    name: "Ahmed",
    github_username: "ahmibr",
    favorite_coding_stack: ["C++", "Python"],
    about_me: "",
  },
  {
    name: "Shoba",
    github_username: "ShobaS",
    favorite_coding_stack: ["HTML", "Javascript", "React"],
    about_me: "",
  },
  {
    name: "Jui",
    github_username: "shahjui2000",
    favorite_coding_stack: ["C++", "Python"],
    about_me: "",
  },
  {
    name: "Tikam Singh Alma",
    github_username: "Tikam02",
    favorite_coding_stack: ["C++", "Python", "Go"],
    about_me: "",
  },
  {
    name: "Pankil Panchal",
    github_username: "pcube99",
    favorite_coding_stack: ["C++", "Python", "Nodejs", "Expressjs", "Reactjs"],
    about_me: "",
  },
  {
    name: "Rafael",
    github_username: "rafagarciac",
    favorite_coding_stack: ["Java", "Python", "Perl", "Data Science", "MiPollaEnVinagre"],
    about_me: "",
  },
  {
    name: "Anmol",
    github_username: "garganmol111",
    favorite_coding_stack: ["C++", "Flutter", "RPA"],
    about_me: "",
  },
  {
    name: "Jeethendra",
    github_username: "JeeBoomBoi",
    favorite_coding_stack: ["C++", "Python", "Angularjs", "Java", "HTML & CSS"],
    about_me: "",
  },
  {
    name: "Abhisht",
    github_username: "abhishtjoshi",
    favorite_coding_stack: ["C++", "JAVA"],
    about_me: "",
  },
  {
    name: "Paras",
    github_username: "parasmannan",
    favorite_coding_stack: ["C++", "C"],
    about_me: "",
  },
  {
    name: "Arun Kumar",
    github_username: "Arun179",
    favorite_coding_stack: ["C++", "Python", "Javascript"],
    about_me: "",
  },
  {
    name: "Edwin Harly",
    github_username: "edwinharly",
    favorite_coding_stack: ["Node.js", "React", "Vue", "Mule ESB"],
    about_me: "",
  },
  {
    name: "Johanes Boas Badia",
    github_username: "boasmarbun",
    favorite_coding_stack: ["Java", "C++", "Python"],
    about_me: "",
  },
  {
    name: "Lenoir Christopher",
    github_username: "xLeDocteurx",
    favorite_coding_stack: ["Javascript", "Php", "C++", "Python"],
    about_me: "",
  },
  {
    name: "Derek",
    github_username: "Quanta770",
    favorite_coding_stack: ["C", "C++", "Java"],
    about_me: "",
  },
  {
    name: "Nori Khan",
    github_username: "naorinn",
    favorite_coding_stack: ["Java", "JavaScript", "SQL"],
    about_me: "",
  },
  {
    name: "dfarley1",
    github_username: "dfarley1",
    favorite_coding_stack: ["C", "C++", "Python"],
    about_me: "",
  },
  {
    name: "Pritesh Tripathi",
    github_username: "priteshtripathi7",
    favorite_coding_stack: ["Node js", "C++", "Javascrip"],
    about_me: "",
  },
  {
    name: "Nguyen",
    github_username: "damdauvaotran",
    favorite_coding_stack: ["Javascript", "Nodejs", "React"],
    about_me: "",
  },
  {
    name: "Nicholas Huber",
    github_username: "nicholashuber",
    favorite_coding_stack: ["Node.js", "React", "React Native"],
    about_me: "",
  },
  {
    name: "Chavez",
    github_username: "joschavz",
    favorite_coding_stack: ["Web Development", "Java", "JavaScript", "PHP"],
    about_me: "",
  },
  {
    name: "Noelie Rx",
    github_username: "noelierx",
    favorite_coding_stack: ["Web Development", "React", "JavaScript"],
    about_me: "",
  },
  {
    name: "Felipe Marques",
    github_username: "FelipeRCMarques",
    favorite_coding_stack: ["Python", "JavaScript", "Java"],
    about_me: "",
  },
  {
    name: "Yash Garg",
    github_username: "yashgarg330",
    favorite_coding_stack: ["Python", "C", "Java"],
    about_me: "",
  },
  {
    name: "Nic",
    github_username: "Frozenaught",
    favorite_coding_stack: ["Python", "JavaScript", "Web Development"],
    about_me: "",
  },
  {
    name: "Koushik Chowdhury",
    github_username: "koushikchowdhury2016",
    favorite_coding_stack: ["Java", "C++", "Python"],
    about_me: "",
  },
  {
    name: "Siwani Agrawal",
    github_username: "siwaniagrawal",
    favorite_coding_stack: ["Python", "JavaScript", "C++"],
    about_me: "",
  },
  {
    name: "Ana Paula Lemos",
    github_username: "anapaulalemos",
    favorite_coding_stack: ["JavaScript", "Typescript"],
    about_me: "",
  },
  {
    name: "Junior Pereira",
    github_username: "pereiraJr",
    favorite_coding_stack: ["Java", "JavaScript", "Python"],
    about_me: "",
  },
  {
    name: "Scout Wallace",
    github_username: "scouttww",
    favorite_coding_stack: ["Python", "JavaScript", "Java", "MATLAB", "LaTeX", "SQL"],
    about_me: "",
  },
  {
    name: "Clint Bowersock",
    github_username: "cbowersock",
    favorite_coding_stack: ["Java", "JavaScript", "Ruby"],
    about_me: "",
  },
  {
    name: "Becca Morse",
    github_username: "BeccaMorse",
    favorite_coding_stack: ["Java", "SQL", "JavaScript", "HTML"],
    about_me: "",
  },
  {
    name: "Katie Oh",
    github_username: "katie-oh",
    favorite_coding_stack: ["Java", "JavaScript", "Vue.js", "SQL", "Svelte"],
    about_me: "",
  },
  {
    name: "Joanne Hyun",
    github_username: "jhyun27",
    favorite_coding_stack: ["Java", "SQL", "Javascript", "HTML", "CSS"],
    about_me: "",
  },
  {
    name: "Kameron Bamforth",
    github_username: "kbamforth2",
    favorite_coding_stack: ["Java", "SQL"],
    about_me: "",
  },
  {
    name: "Andrew Frank",
    github_username: "franklyandy",
    favorite_coding_stack: [
      "C#",
      "JavaScript",
      "SQL",
      "Java",
      "HTML",
      "CSS",
      "Ruby",
      "PHP",
    ],
    about_me: "",
  },
  {
    name: "Kathryn Sanders",
    github_username: "kathryn-sanders",
    favorite_coding_stack: ["C#", "SQL"],
    about_me: "",
  },
  {
    name: "Kaitlynn Steegers",
    github_username: "kaitlynn-steegers",
    favorite_coding_stack: ["Java", "JavaScript", "SQL", "CSS"],
    about_me: "",
  },
  {
    name: "Lucy Festin",
    github_username: "nitseF-L",
    favorite_coding_stack: ["Java", "SQL"],
    about_me: "",
  },
  {
    name: "David Quach",
    github_username: "dquach90",
    favorite_coding_stack: ["Java", "PostgreSQL"],
    about_me: "",
  },
  {
    name: "Bogdan Socaciu",
    github_username: "scbbestof",
    favorite_coding_stack: ["Java", "Go", "MongoDB"],
    about_me: "",
  },
  {
    name: "Brian Fishbaugh",
    github_username: "brianfishbaugh",
    favorite_coding_stack: ["Java", "JavaScript", "SQL", "HTML"],
    about_me: "",
  },
  {
    name: "Nathan Windisch",
    github_username: "natfan",
    favorite_coding_stack: ["PowerShell", "Java", "JavaScript", "SQL", "HTML", "C#"],
    about_me: "",
  },
  {
    name: "Juan Sergio Buenviaje",
    github_username: "lockjio",
    favorite_coding_stack: ["JavaScript", "Python", "C++", "Flutter"],
    about_me: "",
  },
  {
    name: "Eduardo Gusmao",
    github_username: "eduardokum",
    favorite_coding_stack: ["PHP", "JavaScript", "SQL", "Python"],
    about_me: "",
  },
  {
    name: "Amol Kumar",
    github_username: "Rockindash",
    favorite_coding_stack: ["C", "C++", "Swift", "Java", "React"],
    about_me: "",
  },
  {
    name: "Aditya Bajad",
    github_username: "Abajad",
    favorite_coding_stack: ["C++", "python", "HTML"],
    about_me: "",
  },
  {
    name: "Nirmal",
    github_username: "NIRMAL250",
    favorite_coding_stack: ["C", "python", "HTML"],
    about_me: "",
  },
  {
    name: "Sergio Arroyo",
    github_username: "sergioarroyop",
    favorite_coding_stack: ["Bash Scripting", "JavaScript", "HTML"],
    about_me: "",
  },
  {
    name: "Cleo Credo",
    github_username: "credocleo",
    favorite_coding_stack: ["JavaScript", "Python", "C"],
    about_me: "",
  },
  {
    name: "Fz Hasan",
    github_username: "fzhasan",
    favorite_coding_stack: ["PHP", "JS", "HTML"],
    about_me: "",
  },
  {
    name: "Sue Robbins",
    github_username: "Shrobbins",
    favorite_coding_stack: ["JavaScript", "Python"],
    about_me: "",
  },
  {
    name: "Tran Son",
    github_username: "Nos nart",
    favorite_coding_stack: ["React", "Express"],
    about_me: "",
  },
  {
    name: "Rafael",
    github_username: "rafaelgeronimo",
    favorite_coding_stack: ["Javascript", "PHP"],
    about_me: "",
  },
  {
    name: "Eetu Eskelinen",
    github_username: "eppu",
    favorite_coding_stack: ["Vue", "React", "JS", "PHP", "HTML", "CSS"],
    about_me: "",
  },
  {
    name: "Nikola Vrhovac",
    github_username: "vr1e",
    favorite_coding_stack: ["React", "Node", "Ruby on Rails"],
    about_me: "",
  },
  {
    name: "Célien Boillat",
    github_username: "pixlforge",
    favorite_coding_stack: ["Laravel", "Vue", "Nuxt", "TailwindCSS"],
    about_me: "",
  },
  {
    name: "Oscar Navidad",
    github_username: "OskrNav",
    favorite_coding_stack: ["Swift", "IOS", "Ruby On rails"],
    about_me: "",
  },
  {
    name: "Shashank Vaidyar",
    github_username: "shashankvaidyar123",
    favorite_coding_stack: ["Javascript", "C++"],
    about_me: "",
  },
  {
    name: "Surasak Phothiphiphit",
    github_username: "saspallow",
    favorite_coding_stack: ["Golang", "Javascript"],
    about_me: "",
  },
  {
    name: "Jesreal Arcillas",
    github_username: "jarcillas",
    favorite_coding_stack: ["Javascript", "React", "Node"],
    about_me: "",
  },
  {
    name: "breindy",
    github_username: "breindy",
    favorite_coding_stack: ["Javascript", "React", "Node", "Express", "Python"],
    about_me: "",
  },
  {
    name: "Galleria",
    github_username: "Galleria",
    favorite_coding_stack: ["JavaScript", "Java"],
    about_me: "",
  },
  {
    name: "JackyBeatle",
    github_username: "Galleria",
    favorite_coding_stack: ["JavaScript", "Java"],
    about_me: "",
  },
  {
    name: "Pavan Kumar M T",
    github_username: "pavanmt",
    favorite_coding_stack: [
      "Java",
      "Python",
      "NodeJs",
      "Selenium",
      "Alexa",
      "Actions",
      "Docker",
    ],
    about_me: "",
  },
  {
    name: "Constantine",
    github_username: "ckorobov",
    favorite_coding_stack: ["Python", "Ansible", "Terraform", "Bash"],
    about_me: "",
  },
  {
    name: "Leann",
    github_username: "leannkim11",
    favorite_coding_stack: ["JavaScript", "Ruby"],
    about_me: "",
  },
  {
    name: "Danny",
    github_username: "dannynpham",
    favorite_coding_stack: ["JavaScript", "Vue", "Whatever's needed"],
    about_me: "",
  },
  {
    name: "Dyan Carra",
    github_username: "dyancarlos",
    favorite_coding_stack: ["Ruby", "Rails", "Python"],
    about_me: "",
  },
  {
    name: "N.V.Revanth Reddy",
    github_username: "revanth1742",
    favorite_coding_stack: ["java", "JS", "React", "Spring", "Mysql"],
    about_me: "",
  },
  {
    name: "Jaisurya Nanduri",
    github_username: "Jaisu-1",
    favorite_coding_stack: ["Python", "Nodejs", "MongoDB", "Angularjs"],
    about_me: "",
  },
  {
    name: "Phil Swartz",
    github_username: "pswartz66",
    favorite_coding_stack: ["Javascript", "Nodejs", "ReactJS", "Mongodb"],
    about_me: "",
  },
  {
    name: "Jonathan",
    github_username: "jommartinez",
    favorite_coding_stack: ["Javascript", "Nodejs", "ReactJS", "Mongodb"],
    about_me: "",
  },
  {
    name: "Damien Archer",
    github_username: "daarcher04",
    favorite_coding_stack: ["Python", "C#", "Objective C", "Swift"],
    about_me: "",
  },
  {
    name: "Pedro Alecrim",
    github_username: "pedroalecrim",
    favorite_coding_stack: ["Markdown", "Information Architecture"],
    about_me: "",
  },
  {
    name: "Athul Joy",
    github_username: "iathul",
    favorite_coding_stack: ["JavaScript", "NodeJS", "Angular", "React"],
    about_me: "",
  },
  {
    name: "Andrey Kudryavtsev",
    github_username: "cat-street",
    favorite_coding_stack: ["JavaScript", "React", "CSS"],
    about_me: "",
  },
  {
    name: "Ramanujam Gond",
    github_username: "ramanujamgond",
    favorite_coding_stack: ["JavaScript", "ReactJs", "Dart", "C++"],
    about_me: "",
  },
  {
    name: "Michelle Tanoto",
    github_username: "tanoto-the-explorer",
    favorite_coding_stack: ["JavaScript", "React Native", "NodeJS"],
    about_me: "",
  },
  {
    name: "Ankit Lenka",
    github_username: "AnkitLenka26",
    favorite_coding_stack: ["NodeJs", "C++", "JavaScript", "React"],
    about_me: "",
  },
  {
    name: "Chirag Sharma",
    github_username: "ChiragSharma1",
    favorite_coding_stack: ["JavaScript", "Python", "C++"],
    about_me: "",
  },
  {
    name: "Sagar Utekar",
    github_username: "Sagar2366",
    favorite_coding_stack: ["Cloud", "DevOps", "Python"],
    about_me: "",
  },
  {
    name: "Breno Santos",
    github_username: "breno5g",
    favorite_coding_stack: ["NodeJs", "React", "JavaScript"],
    about_me: "",
  },
  {
    name: "Naruedom Tongkampan",
    github_username: "dreaminfo",
    favorite_coding_stack: ["JS"],
    about_me: "",
  },
  {
    name: "Edilson Matola",
    github_username: "edilsonmatola",
    favorite_coding_stack: ["Flutter", "React.js", "Next.js"],
    about_me: "",
  },
  {
    name: "Hisham",
    github_username: "HeshamCaesar001",
    favorite_coding_stack: [
      "MongoDB",
      "Express",
      "NodeJS",
      "NestJS",
      "PostgresSQL",
      "Javascript",
      "Typescript",
    ],
    about_me: "",
  },
];
